language: java
jdk:
  - oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer

after_success:
  - mvn --batch-mode deploy -Dmaven.test.skip -DcreateDocs=true -s settings.xml
  - mvn --batch-mode jacoco:report coveralls:jacoco -DsourceEncoding=UTF-8
